### ISSUE TITLE
Error on retrieving building blocks list on core API

### ISSUE THREAD

**Issue by arno-di-loreto** [kinlane/developer-api-evangelist#1]
When retrieving building blocks list there's an error:

Request URL: http://api.apievangelist.com:80/v1/buildingblock/types?appid=XXXXX&appkey=YYYYY
Response Body: Query failed: Unknown column 'types' in 'where clause'

**Comment by kinlane** [comment]
Sorry for being such a slacker on this. I fixed it, but the new API should be finished this week too. It will have more endpoints.
